$(document).ready(function () {indexDict['en'] = [{ "title" : "Welcome ", 
"url" : "welcome.html", 
"breadcrumbs" : "GA Test \/ Welcome ", 
"snippet" : "Welcome! We don't have too much more to say here aside from welcome. So consider yourself welcome and make yourself at home....", 
"body" : "Welcome! We don't have too much more to say here aside from welcome. So consider yourself welcome and make yourself at home. " }, 
{ "title" : "About Us ", 
"url" : "about-us.html", 
"breadcrumbs" : "GA Test \/ About Us ", 
"snippet" : "We are a group of structured authoring enthusiasts and we really enjoy our work....", 
"body" : "We are a group of structured authoring enthusiasts and we really enjoy our work. " }, 
{ "title" : "Contact ", 
"url" : "contact.html", 
"breadcrumbs" : "GA Test \/ Contact ", 
"snippet" : "You may contact us through one of the following methods: Smoke signals Bat signal Carrier Pigeon Morse Code Megaphone...", 
"body" : "You may contact us through one of the following methods: Smoke signals Bat signal Carrier Pigeon Morse Code Megaphone " }, 
{ "title" : "Eggnog ", 
"url" : "eggnog.html", 
"breadcrumbs" : "GA Test \/ Eggnog ", 
"snippet" : "All of our employees enjoy unlimited fresh eggnog as a company benefit....", 
"body" : "All of our employees enjoy unlimited fresh eggnog as a company benefit. " }, 
{ "title" : "Infrequently Asked Questions ", 
"url" : "infrequently-asked-questions.html", 
"breadcrumbs" : "GA Test \/ Infrequently Asked Questions ", 
"snippet" : "If tin whistles are made of tin what do they make foghorns out of? Is the statement \"There is no absolute truth!\" a true statement? How do you dig half a hole?...", 
"body" : "If tin whistles are made of tin what do they make foghorns out of? Is the statement \"There is no absolute truth!\" a true statement? How do you dig half a hole? " }
]
$(document).trigger('search.ready');
});